apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wf-app
  namespace: writersfund
  labels:
    app: wf-app
    app.kubernetes.io/name: wf-app
    app.kubernetes.io/component: backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://garretstreet.com"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: writersfund.vc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wf-app
                port:
                  number: 80
  tls:
    - hosts:
        - writersfund.vc
      secretName: writersfund-tls